package com.example.domaci2.catListP.mappers

import com.example.domaci2.catListP.api.model.CatApiModel
import com.example.domaci2.catListP.db.Cat

fun CatApiModel.asCatDbModel(): Cat {
    return Cat(
        id = this.id,
        name = this.name,
        cfa_url = this.cfa_url,
        vetstreet_url = this.vetstreet_url,
        vcahospitals_url = this.vcahospitals_url,
        temperament = this.temperament,
        origin = this.origin,
        country_codes = this.country_codes,
        country_code = this.country_code,
        description = this.description,
        life_span = this.life_span,
        indoor = this.indoor,
        lap = this.lap,
        alt_names = this.alt_names,
        adaptability = this.adaptability,
        affection_level = this.affection_level,
        child_friendly = this.child_friendly,
        dog_friendly = this.dog_friendly,
        energy_level = this.energy_level,
        grooming = this.grooming,
        health_issues = this.health_issues,
        intelligence = this.intelligence,
        shedding_level = this.shedding_level,
        social_needs = this.social_needs,
        stranger_friendly = this.stranger_friendly,
        vocalisation = this.vocalisation,
        experimental = this.experimental,
        hairless = this.hairless,
        natural = this.natural,
        rare = this.rare,
        rex = this.rex,
        suppressed_tail = this.suppressed_tail,
        short_legs = this.short_legs,
        wikipedia_url = this.wikipedia_url,
        hypoallergenic = this.hypoallergenic,
        reference_image_id = this.reference_image_id,
        url = this.url,
        imperial = this.imperial,
        metric = this.metric,
    )
}
/*
val id: String,
    val name: String,
    val cfa_url: String? = null,
    val vetstreet_url: String? = null,
    val vcahospitals_url: String? = null,
    val temperament: String,
    val origin: String,
    val country_codes: String,
    val country_code: String,
    val description: String,
    val life_span: String,
    val indoor: Int,
    val lap: Int? = null,
    val alt_names: String = "",
    val adaptability: Int,
    val affection_level: Int,
    val child_friendly: Int,
    val dog_friendly: Int,
    val energy_level: Int,
    val grooming: Int,
    val health_issues: Int,
    val intelligence: Int,
    val shedding_level: Int,
    val social_needs: Int,
    val stranger_friendly: Int,
    val vocalisation: Int,
    val experimental: Int,
    val hairless: Int,
    val natural: Int,
    val rare: Int,
    val rex: Int,
    val suppressed_tail: Int,
    val short_legs: Int,
    val wikipedia_url: String? = null,
    val hypoallergenic: Int,
    val reference_image_id: String? = null,
    val url: String = "",
    val weight: Weight,
 */